### ISSUE TITLE
Sign up / Log in Workflow

### ISSUE THREAD

**Issue by lehman** [upward-dev/Upward#26]
**Overview**: Create a Sign up / Log in workflow on upward.dev for users to be able to create an account.

**Notes**:
There is another Issue that says the users table will have these columns:
`authentication_method` and `is_mentor`

If that is the case, then always set these default values for now:
- `is_mentor` to `false`
- `authentication_method` to `null`

**Acceptance Criteria**:
GIVEN the user is on any page of the site
THEN there is a **Sign up** button and a **Log in** button in the top right of the page

WHEN a user clicks the Sign up button
THEN they are taken to a new Sign up page in the site with the following input fields: first name, last name, email, and password, and a button that says "Sign up"

WHEN a user clicks the Log in button
THEN they are taken to a new Log in page in the site with input fields for email and password, and a button that says "Log in"

GIVEN the user is on the Sign up page
AND has not entered a valid first, last, email, and password
WHEN they click the "Sign up" button
THEN the input fields with invalid input are outlined in red and have an error message in red text below the relevant fields

GIVEN the user is on the Sign up page
AND has entered a valid first, last, email, and password
WHEN they click the "Sign up" button
THEN their data is inserted into the users table
AND they are redirected to the home page
AND the Sign up and Log in buttons are gone
AND in the top right there is their name and a user icon to the right of their name

GIVEN the user is on the Log in page
AND has entered a valid email and password
WHEN they click the "Log in" button
THEN they are redirected to the home page
AND the Sign up and Log in buttons are gone
AND in the top right there is their name and a user icon to the right of their name

GIVEN the user is on the Log in page
AND has entered an email that doesn't exist
WHEN they click the "Log in" button
THEN there is a red banner message inline that says "We didn't find an account with that email."

GIVEN the user is on the Log in page
AND has entered an email that does exist but has not entered a password
WHEN they click the "Log in" button
THEN the password field is outlined in red and there is an error message in red text below that says "Password is required."

GIVEN the user is on the Log in page
AND has entered an invalid password for email that does exist
WHEN they click the "Log in" button
THEN there is a red banner message inline that says "Invalid password"

**Field Validation**
- Fields can't be empty
- Max 100 chars for all fields
- Accept special characters / chars in other languages for name fields
- Email must be valid email format
- Password must be at least 8 characters long and not be their first, last, or email

**Error Messages**
- On empty field: "<field label> is a required field."
- On email with invalid format: "Must be a valid email."
- On trying to type a char over the char limit: "<field label> has a max 100 character limit."
- On invalid password: "Password must be at least 8 characters long and not be your first/last name or email."

**Comment by ainneo** [comment]
closed issue - issue was already worked on by another teammate
